redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
#secret: fbrn02
bind-address: "*"
unified-delay: true
external-ui: "/data/adb/box/clash/dashboard
experimental:
  ignore-resolve-fail: true
ipv6: false
tun:
  enable: true
  stack: system
  device: utun
  mtu: 65535
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
  - tcp://any:53
profile:
  store-selected: true
  store-fakeip: true
  store-fake-ip: false