tproxy-port: 9898
redir-port: 9797
port: 7890
socks-port: 7891
mixed-port: 7893
bind-address: "*"
mode: rule
allow-lan: true
log-level: silent
external-controller: 0.0.0.0:9090
external-ui: ui/yacd-gh-pages
unified-delay: true
ipv6: false
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.0/8
  use-hosts: true
  nameserver:
    - https://cloudflare-dns.com/dns-query


proxies:
proxy-groups:
- name: BOOST
  type: select
  disable-udp: false
  proxies:
  - AUTO ROUTE
  - DIRECT
  - DIRECT usb0
  use:
  - Akun
  url: http://cp.cloudflare.com/generate_204
  interval: '1'
- name: DIRECT1
  type: select
  disable-udp: false
  proxies:
  - BOOST
  - DIRECT
  - REJECT
  url: http://cp.cloudflare.com/generate_204
  interval: '1'
- name: Game-Turbo
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - BOOST
  - REJECT
  url: http://cp.cloudflare.com/generate_204
  interval: '1'
 # (usb0) interface: eth1 wlan0 eth2 usb0
- name: DIRECT usb0
  type: select
  disable-udp: false
  interface-name: usb0
  proxies:
  - DIRECT
  url: https://cp.cloudflare.com/generate_204
  interval: '1'

- name: TrafficAds
  type: select
  disable-udp: false
  proxies:
  - BOOST
  - REJECT
  url: https://cp.cloudflare.com/generate_204
  interval: '1'
- name: TrafficPorn
  type: select
  disable-udp: false
  proxies:
  - REJECT
  - BOOST
  url: https://cp.cloudflare.com/generate_204
  interval: '1'

- name: AUTO ROUTE
  type: fallback
  disable-udp: false
  use:
  - Akun
  url: https://cp.cloudflare.com/generate_204
  interval: '1'
  lazy: false

proxy-providers:
  Akun:
    type: http
    url: "https://raw.githubusercontent.com/GetPush/Clash/main/usr/Kboy/Akun.yaml"
    path: "./proxy_provider/Online/Akun.yaml"
    health-check:
      enable: true
    interval: 12000

rules:
- RULE-SET,rule_reject,REJECT
- RULE-SET,rule_malicious,REJECT
- RULE-SET,rule_maliciousip,REJECT

- RULE-SET,rule_adblock,REJECT
- RULE-SET,rule_oisd_big,REJECT

- RULE-SET,rule_basicads,TrafficAds
- RULE-SET,rule_hijacking,TrafficAds
- RULE-SET,rule_privacy,TrafficAds

#   - GEOSITE,oisd-full,TrafficAds
#   - GEOSITE,rule-ads,TrafficAds

- DOMAIN-SUFFIX,pagead2.googlesyndication.com,BOOST
#- DOMAIN-SUFFIX,video-ad-stats.googlesyndication.com,BOOST
- DOMAIN-SUFFIX,googlesyndication.com,BOOST
#- DOMAIN-SUFFIX,www3.doubleclick.net,BOOST

- RULE-SET,rule_porn,TrafficPorn
- RULE-SET,rule_nsfw,TrafficPorn

- DST-PORT,5228BOOST
- RULE-SET,rule_discord,Game-Turbo
- RULE-SET,games,Game-Turbo
- RULE-SET,game,Game-Turbo
- RULE-SET,gameu,Game-Turbo
- RULE-SET,mlm,Game-Turbo
- RULE-SET,gm,Game-Turbo
- RULE-SET,rule_portgames,Game-Turbo
- RULE-SET,rule_portgametcp,Game-Turbo
- RULE-SET,rule_portgameudp,Game-Turbo
- RULE-SET,rule_PortTCP,Game-Turbo
- RULE-SET,rule_PortUDP,Game-Turbo

- MATCH,BOOST


rule-providers:
#adblock
  rule_malicious:
    type: file
    behavior: domain
    url: https://raw.githubusercontent.com/GetPush/Clash/main/rule_provider/adblock/rule_malicious.yaml
    path: "./rule_provider/adblock/rule_malicious.yaml"
    interval: 43200
  rule_maliciousip:
    type: file
    behavior: ipcidr
    url: https://raw.githubusercontent.com/GetPush/Clash/main/rule_provider/adblock/rule_maliciousip.yaml
    path: "./rule_provider/adblock/rule_maliciousip.yaml"
    interval: 43200
  rule_reject:
    type: file
    behavior: classical
    path: "./rule_provider/adblock/rule_reject.yaml"
    url: https://raw.githubusercontent.com/GetPush/Clash/main/rule_provider/adblock/rule_reject.yaml
    interval: 86400
  rule_oisd_big:
    type: file
    behavior: classical
    url: https://raw.githubusercontent.com/GetPush/Clash/main/rule_provider/adblock/rule_oisd_big.yaml
    path: "./rule_provider/adblock/rule_oisd_big.yaml"
    interval: 86400
  rule_basicads:
    type: file
    behavior: domain
    url: https://raw.githubusercontent.com/GetPush/Clash/main/rule_provider/adblock/rule_basicads.yaml
    path: "./rule_provider/adblock/rule_basicads.yaml"
    interval: 43200
  rule_hijacking:
    type: file
    behavior: classical
    path: "./rule_provider/adblock/rule_hijacking.yaml"
    url: https://raw.githubusercontent.com/GetPush/Clash/main/rule_provider/adblock/rule_hijacking.yaml
    interval: 86400
  rule_privacy:
    type: file
    behavior: classical
    url: https://raw.githubusercontent.com/GetPush/Clash/main/rule_provider/adblock/rule_privacy.yaml
    path: "./rule_provider/adblock/rule_privacy.yaml"
    interval: 86400

  rule_adblock:
    type: file
    behavior: classical
    url: https://raw.githubusercontent.com/GetPush/Clash/main/rule_provider/adblock/rule_adblock.yaml
    path: "./rule_provider/adblock/rule_adblock.yaml"
    interval: 86400


#porn
  rule_porn:
    type: file
    behavior: domain
    url: https://raw.githubusercontent.com/GetPush/Clash/main/rule_provider/porn/rule_porn.yaml
    path: "./rule_provider/porn/rule_porn.yaml"
    interval: 86400
  rule_nsfw:
    type: file
    behavior: domain
    url: https://raw.githubusercontent.com/GetPush/Clash/main/rule_provider/porn/rule_nsfw.yaml
    path: "./rule_provider/porn/rule_nsfw.yaml"
    interval: 43200

# game

  rule_discord:
    type: file
    behavior: classical
    url: https://raw.githubusercontent.com/GetPush/Clash/main/rule_provider/games/rule_discord.yaml
    path: "./rule_provider/games/rule_discord.yaml"
    interval: 43200
  games:
    type: file
    behavior: classical
    url: https://raw.githubusercontent.com/GetPush/Clash/main/rule_provider/games/rule_games.yaml
    path: "./rule_provider/games//rule_games.yaml"
    interval: 43200
  gm:
    type: file
    behavior: classical
    url: https://raw.githubusercontent.com/GetPush/Clash/main/rule_provider/games/rule_GamesMax.yaml
    path: "./rule_provider/games/rule_GamesMax.yaml"
    interval: 43200
  gameu:
    type: file
    behavior: classical
    url: https://raw.githubusercontent.com/GetPush/Clash/main/rule_provider/games/rule_gameumum.yaml
    path: "./rule_provider/games/rule_gameumum.yaml"
    interval: 43200
  game:
    type: file
    behavior: classical
    url: https://raw.githubusercontent.com/GetPush/Clash/main/rule_provider/games/rule_gaming.yaml
    path: "./rule_provider/games/rule_gaming.yaml"
    interval: 43200
  mlm:
    type: file
    behavior: classical
    url: https://raw.githubusercontent.com/GetPush/Clash/main/rule_provider/games/rule_MobileLegend.yaml
    path: "./rule_provider/games/rule_MobileLegend.yaml"
    interval: 43200
  rule_portgames:
    type: file
    behavior: classical
    url: https://raw.githubusercontent.com/GetPush/Clash/main/rule_provider/games/rule_portgames.yaml
    path: "./rule_provider/games/rule_portgames.yaml"
    interval: 43200
  rule_portgametcp:
    type: file
    behavior: classical
    url: https://raw.githubusercontent.com/GetPush/Clash/main/rule_provider/games/rule_portgametcp.yaml
    path: "./rule_provider/games/rule_portgametcp.yaml"
    interval: 43200
  rule_portgameudp:
    type: file
    behavior: classical
    url: https://raw.githubusercontent.com/GetPush/Clash/main/rule_provider/games/rule_portgameudp.yaml
    path: "./rule_provider/games/rule_portgameudp.yaml"
    interval: 43200
  rule_PortTCP:
    type: file
    behavior: classical
    url: https://raw.githubusercontent.com/GetPush/Clash/main/rule_provider/games/rule_PortTCP.yaml
    path: "./rule_provider/games/rule_PortTCP.yaml"
    interval: 43200
  rule_PortUDP:
    type: file
    behavior: classical
    url: https://raw.githubusercontent.com/GetPush/Clash/main/rule_provider/games/rule_PortUDP.yaml
    path: "./rule_provider/games/rule_PortUDP.yaml"
    interval: 43200

  direct:
    type: file
    behavior: classical
    url: https://raw.githubusercontent.com/GetPush/Clash/main/rule_provider/rule_direct.yaml
    path: "./rule_provider/rule_direct.yaml"
    interval: 43200